baseURL: 'https://kushalhomeopathy.netlify.app/'
languageCode: 'en-us'
title: 'Kushal Homeopathy'
paginate: 6
# social:
#   twitter: '#'
#   github: '#'
#   instagram: '#'
#   linkedin: '#'
#   dribbble: '#'
#   youtube: '#'
taxonomies:
  author: authors
theme: 'novela'
